export const KEY_PAGE = {
  SET_INTERNET: 'SET_INTERNET',
  SET_TIME: 'SET_TIME',
  SET_PANTOGRAPH: 'SET_PANTOGRAPH',
  SET_METAMASK_INFO: 'SET_METAMASK_INFO',
  SET_WALLET_CONNECT: 'SET_WALLET_CONNECT',
  SET_BALANCE: 'SET_BALANCE',
}
